site_name: 学习笔记

nav:
  - 文档说明:
    - 文档来源: index.md
    - 使用说明: 笔记使用/笔记使用.md
  - 数学:
      - Latex: 数学公式/Markdown写作方法.md
  - 英语:
      - 名词: 英语/名词.md
      - 代词: 英语/代词.md
  - 深度学习:
      - 深度学习: 深度学习/环境安装.md
  - Python:
    - Jupyter: 项目部署/Jupyter.md

theme:
  name: material
  features:
    - instant
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true



extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css

extra:
  mathjax:
    tex:
      tags: 'ams'  # 启用 AMS 标签支持
      processEscapes: true

plugins:
  - search